spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://config-server:8888"
    retry: # Agregamos esto para que sea paciente
      enabled: true
      initial-interval: 3000
      max-attempts: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Configuración moderna para evitar errores de metadatos en el arranque
        boot:
          allow_jdbc_metadata_access: false
  datasource:
    url: jdbc:mysql://auth-db:3306/auth_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: meditech-super-secret-key-must-be-at-least-256-bits-long
  expiration: 86400000

server:
  port: 8081