spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://config-server:8888"
    retry:
      enabled: true
      initial-interval: 3000
      max-attempts: 10

  # Esto le dice a Spring que no falle si la BD no está disponible al arrancar
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Configuración moderna para evitar errores de metadatos en el arranque
        boot:
          allow_jdbc_metadata_access: false
  datasource:
    url: jdbc:mysql://product-db:3306/product_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8082