spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: purchase-service
          uri: lb://purchase-service
          predicates:
            - Path=/api/purchases/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

server:
  port: 8080

eureka:
  instance:
    # Esto permite que el Gateway encuentre los servicios por IP
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:meditech-super-secret-key-must-be-at-least-256-bits-long}
  expiration: 86400000

management:
  endpoint:
    gateway:
      enabled: true # ESTA LÍNEA ES CLAVE para que aparezca la ruta
  endpoints:
    web:
      exposure:
        include: gateway, health, info